"""employees table

Revision ID: ae3df4dbe7ff
Revises: 9a6942aebf83
Create Date: 2018-10-20 08:51:26.074534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae3df4dbe7ff'
down_revision = '9a6942aebf83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=140), nullable=True),
    sa.Column('last_name', sa.String(length=140), nullable=True),
    sa.Column('hire_date', sa.DateTime(), nullable=True),
    sa.Column('salary', sa.Integer(), nullable=True),
    sa.Column('department', sa.String(length=140), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_hire_date'), 'employee', ['hire_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employee_hire_date'), table_name='employee')
    op.drop_table('employee')
    # ### end Alembic commands ###
